version: "3.3"

services:
  cli:
    build: .
    container_name: ma_cli
    volumes:
      - ./:/src/

  adminer:
    image: adminer
    container_name: ma_adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: hydra
      ADMINER_DEFAULT_SERVER: ma_mysql

  mysql:
    image: mysql
    container_name: ma_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_DATABASE: mudae_auctions
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d

networks:
  default:
      name: "mudaeAuctions"
  