version: "3.3"

services:
  adminer:
    image: adminer
    container_name: ma_adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: hydra
      ADMINER_DEFAULT_SERVER: ma_mysql

  mysql:
    image: mysql
    container_name: ma_mysql
    command: >
      --default-authentication-plugin=mysql_native_password &&
      sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
      echo $TZ > /etc/timezone"
    restart: on-failure
    environment:
      MYSQL_DATABASE: mudae_auctions
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Paris
    ports:
      - 3306:3306

networks:
  default:
      name: "mudaeAuctions"
  